//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPE.Trains.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPE.Trains.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_next {
            get {
                object obj = ResourceManager.GetObject("arrow_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_prev {
            get {
                object obj = ResourceManager.GetObject("arrow_prev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;book_list-item&quot; data-book=&quot;{Identifier}&quot;&gt;
        ///    &lt;div class=&quot;bk-img&quot;&gt;
        ///        &lt;div class=&quot;bk-wrapper&quot;&gt;
        ///            &lt;div class=&quot;book-item&quot;&gt;
        ///                &lt;div class=&quot;bk-book bk-bookdefault&quot;&gt;
        ///                    &lt;div class=&quot;bk-front&quot;&gt;
        ///                        &lt;div class=&quot;bk-cover&quot;&gt;&lt;img src=&quot;{Thumbnail}&quot; /&gt;&lt;/div&gt;
        ///                    &lt;/div&gt;
        ///                    &lt;div class=&quot;bk-back&quot;&gt;&lt;/div&gt;
        ///                    &lt;div class=&quot;bk-left&quot;&gt;&lt;img src=&quot;{Thumbnail}&quot; /&gt;&lt;/div&gt;
        ///                &lt;/div&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BookItem {
            get {
                return ResourceManager.GetString("BookItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///	&lt;img src=&quot;{ImageUrl}&quot; /&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string BookletImage {
            get {
                return ResourceManager.GetString("BookletImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div data-book=&quot;{Identifier}&quot; style=&quot;display: none;&quot;&gt;
        ///    &lt;div class=&quot;b-load&quot;&gt;
        ///        &lt;div&gt;
        ///            &lt;h1&gt;{Description}&lt;/h1&gt;
        ///            &lt;p&gt;{Year}&lt;/p&gt;
        ///            &lt;p&gt;{Manufacturer}&lt;/p&gt;
        ///        &lt;/div&gt;
        ///        {Images}
        ///    &lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string BookletImages {
            get {
                return ResourceManager.GetString("BookletImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] closedhand {
            get {
                object obj = ResourceManager.GetObject("closedhand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Courgette_Regular {
            get {
                object obj = ResourceManager.GetObject("Courgette_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v2.1.0 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k=&quot;&quot;.trim,l={},m=a.document,n=&quot;2.1.0&quot;,o=function(a,b){return new o.fn.init(a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_2_1_0_min {
            get {
                return ResourceManager.GetString("jquery_2_1_0_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jQuery Booklet Plugin
        /// * Copyright (c) 2010 - 2014 William Grauvogel (http://builtbywill.com/)
        /// *
        /// * Licensed under the MIT license (http://www.opensource.org/licenses/mit-license.php)
        /// *
        /// * Version : 1.4.4
        /// *
        /// * Originally based on the work of:
        /// *	1) Charles Mangin (http://clickheredammit.com/pageflip/)
        /// */
        ///;(function(a){a.fn.booklet=function(k,f,d){var i,c,h,g,l,e,j;if(typeof k===&quot;string&quot;){l=[];a(this).each(function(){i=a(this).data(&quot;booklet&quot;);if(i){c=k;h=[];if(typeof f!==&quot;undefined&quot;){h.push(f)}if(t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_booklet_latest_min {
            get {
                return ResourceManager.GetString("jquery_booklet_latest_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jQuery Booklet Plugin
        /// * Copyright (c) 2010 - 2014 William Grauvogel (http://builtbywill.com/)
        /// *
        /// * Licensed under the MIT license (http://www.opensource.org/licenses/mit-license.php)
        /// *
        /// * Version : 1.4.4
        /// *
        /// * Originally based on the work of:
        /// *	1) Charles Mangin (http://clickheredammit.com/pageflip/)
        /// */
        ///	.booklet         {width:800px; height:600px; position:relative; margin:0 auto 10px; overflow:visible !important;}
        ///	.booklet .b-page {left:0; top:0; position:absolute; overflow:hidden; padding:0;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_booklet_latestCss {
            get {
                return ResourceManager.GetString("jquery_booklet_latestCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jQuery Booklet Plugin
        /// * Copyright (c) 2010 - 2014 William Grauvogel (http://builtbywill.com/)
        /// *
        /// * Licensed under the MIT license (http://www.opensource.org/licenses/mit-license.php)
        /// *
        /// * Version : 1.4.4
        /// *
        /// * Originally based on the work of:
        /// *	1) Charles Mangin (http://clickheredammit.com/pageflip/)
        /// */
        ///;(function ($) {
        ///
        ///    $.fn.booklet = function (options, param1, param2) {
        ///
        ///        var obj, method, params, output, result, config, index;
        ///
        ///        // option type string - api call
        ///        if (typ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_booklet_latestJs {
            get {
                return ResourceManager.GetString("jquery_booklet_latestJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * jQuery Easing v1.3 - http://gsgd.co.uk/sandbox/jquery/easing/
        /// *
        /// * Uses the built in easing capabilities added In jQuery 1.1
        /// * to offer multiple easing options
        /// *
        /// * TERMS OF USE - jQuery Easing
        /// * 
        /// * Open source under the BSD License. 
        /// * 
        /// * Copyright Â© 2008 George McGinley Smith
        /// * All rights reserved.
        /// * 
        /// * Redistribution and use in source and binary forms, with or without modification, 
        /// * are permitted provided that the following conditions are met:
        /// * 
        /// * Redistributions of source code mus [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_easing_1_3 {
            get {
                return ResourceManager.GetString("jquery_easing_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery UI - v1.10.4 - 2014-01-17
        ///* http://jqueryui.com
        ///* Includes: jquery.ui.core.js, jquery.ui.widget.js, jquery.ui.mouse.js, jquery.ui.position.js, jquery.ui.accordion.js, jquery.ui.autocomplete.js, jquery.ui.button.js, jquery.ui.datepicker.js, jquery.ui.dialog.js, jquery.ui.draggable.js, jquery.ui.droppable.js, jquery.ui.effect.js, jquery.ui.effect-blind.js, jquery.ui.effect-bounce.js, jquery.ui.effect-clip.js, jquery.ui.effect-drop.js, jquery.ui.effect-explode.js, jquery.ui.effect-fade.js, jquery.ui [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_ui_1_10_4_min {
            get {
                return ResourceManager.GetString("jquery_ui_1_10_4_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap left_bg {
            get {
                object obj = ResourceManager.GetObject("left_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] openhand {
            get {
                object obj = ResourceManager.GetObject("openhand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Raleway_Regular {
            get {
                object obj = ResourceManager.GetObject("Raleway_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right_bg {
            get {
                object obj = ResourceManager.GetObject("right_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shadow {
            get {
                object obj = ResourceManager.GetObject("shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shadow_top_back {
            get {
                object obj = ResourceManager.GetObject("shadow_top_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shadow_top_forward {
            get {
                object obj = ResourceManager.GetObject("shadow_top_forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;WPE Trains Gallery&lt;/title&gt;
        ///    &lt;script src=&quot;booklet/jquery-2.1.0.min.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;booklet/jquery-ui-1.10.4.min.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;booklet/jquery.easing.1.3.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;booklet/jquery.booklet.latest.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SiteLayout {
            get {
                return ResourceManager.GetString("SiteLayout", resourceCulture);
            }
        }
    }
}
